export interface OmniwxEnv {
  DB?: D1Database;
  NOAA_NCEI_TOKEN: string;
  NASA_API_KEY: string;
  AIRNOW_API_KEY?: string;
  NASA_FIRMS_MAP_KEY?: string;
  RADAR_IEM_WMS_BASE?: string;
  RADAR_BACKEND_MODE?: string;
  RADAR_BACKEND_BASE_URL?: string;
  RADAR_BACKEND_MANIFEST_URL?: string;
  RADAR_BACKEND_TIMELINE_URL?: string;
  RADAR_BACKEND_MOSAIC_TILES_URL?: string;
  RADAR_BACKEND_RIDGE_TILES_URL?: string;
  RADAR_BACKEND_WMS_URL?: string;
  RADAR_MANIFEST_INGEST_ENABLED?: string;
  RADAR_MANIFEST_INGEST_MAX_FRAMES?: string;
  RADAR_MANIFEST_INGEST_INCLUDE_NOWCAST?: string;
}
