// AUTO-GENERATED by scripts/generate-land-points.mjs
// Do not edit by hand.
// version: v3-airports200-cities200-capitals-global-notables

export const LAND_POINTS_VERSION = "v3-airports200-cities200-capitals-global-notables" as const;

export type LandPoint = {
  id: string;
  name: string;
  lat: number;
  lon: number;
  badge?: "US" | "Global";
  group?: "airport" | "capital" | "city" | "notable";
};

export const LAND_POINTS: LandPoint[] = [
  {
    "id": "us-city-new-york-metropolitan-area",
    "name": "New York metropolitan area",
    "lat": 40.808611111,
    "lon": -74.020277777,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-new-york-city",
    "name": "New York City",
    "lat": 40.712777777,
    "lon": -74.006111111,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-los-angeles",
    "name": "Los Angeles",
    "lat": 34.05223,
    "lon": -118.24368,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-chicago",
    "name": "Chicago",
    "lat": 41.881944444,
    "lon": -87.627777777,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-el-paso-ju-rez",
    "name": "El Paso–Juárez",
    "lat": 31.73944444,
    "lon": -106.48694444,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-queens",
    "name": "Queens",
    "lat": 40.713611111,
    "lon": -73.828055555,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-houston",
    "name": "Houston",
    "lat": 29.762777777,
    "lon": -95.383055555,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-manhattan",
    "name": "Manhattan",
    "lat": 40.728333333,
    "lon": -73.994166666,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-phoenix",
    "name": "Phoenix",
    "lat": 33.448333333,
    "lon": -112.073888888,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-philadelphia",
    "name": "Philadelphia",
    "lat": 39.952777777,
    "lon": -75.163611111,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-the-bronx",
    "name": "The Bronx",
    "lat": 40.846666666,
    "lon": -73.873333333,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-san-antonio",
    "name": "San Antonio",
    "lat": 29.425,
    "lon": -98.493888888,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-san-diego",
    "name": "San Diego",
    "lat": 32.715,
    "lon": -117.1625,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-dallas",
    "name": "Dallas",
    "lat": 32.779166666,
    "lon": -96.808888888,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-san-jose",
    "name": "San Jose",
    "lat": 37.304166666,
    "lon": -121.872777777,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-austin",
    "name": "Austin",
    "lat": 30.3,
    "lon": -97.733333333,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-jacksonville",
    "name": "Jacksonville",
    "lat": 30.316666666,
    "lon": -81.65,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-fort-worth",
    "name": "Fort Worth",
    "lat": 32.756388888,
    "lon": -97.3325,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-columbus",
    "name": "Columbus",
    "lat": 39.962222222,
    "lon": -83.000555555,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-indianapolis",
    "name": "Indianapolis",
    "lat": 39.768611111,
    "lon": -86.158055555,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-charlotte",
    "name": "Charlotte",
    "lat": 35.226944444,
    "lon": -80.843333333,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-san-francisco",
    "name": "San Francisco",
    "lat": 37.775,
    "lon": -122.419444444,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-seattle",
    "name": "Seattle",
    "lat": 47.605,
    "lon": -122.33,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-denver",
    "name": "Denver",
    "lat": 39.739166666,
    "lon": -104.984722222,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-washington-d-c",
    "name": "Washington, D.C.",
    "lat": 38.895,
    "lon": -77.036666666,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-nashville",
    "name": "Nashville",
    "lat": 36.162222222,
    "lon": -86.774444444,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-oklahoma-city",
    "name": "Oklahoma City",
    "lat": 35.482222222,
    "lon": -97.535277777,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-el-paso",
    "name": "El Paso",
    "lat": 31.759166666,
    "lon": -106.488611111,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-boston",
    "name": "Boston",
    "lat": 42.360277777,
    "lon": -71.057777777,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-portland",
    "name": "Portland",
    "lat": 45.516666666,
    "lon": -122.666666666,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-las-vegas",
    "name": "Las Vegas",
    "lat": 36.167222222,
    "lon": -115.148611111,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-detroit",
    "name": "Detroit",
    "lat": 42.331666666,
    "lon": -83.0475,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-memphis",
    "name": "Memphis",
    "lat": 35.146111111,
    "lon": -90.051944444,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-baltimore",
    "name": "Baltimore",
    "lat": 39.286388888,
    "lon": -76.615,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-milwaukee",
    "name": "Milwaukee",
    "lat": 43.05,
    "lon": -87.95,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-albuquerque",
    "name": "Albuquerque",
    "lat": 35.084444444,
    "lon": -106.650277777,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-tucson",
    "name": "Tucson",
    "lat": 32.221666666,
    "lon": -110.926388888,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-fresno",
    "name": "Fresno",
    "lat": 36.781666666,
    "lon": -119.792222222,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-sacramento",
    "name": "Sacramento",
    "lat": 38.575277777,
    "lon": -121.486111111,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-kansas-city",
    "name": "Kansas City",
    "lat": 39.05,
    "lon": -94.583333333,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-mesa",
    "name": "Mesa",
    "lat": 33.415,
    "lon": -111.831388888,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-atlanta",
    "name": "Atlanta",
    "lat": 33.754444444,
    "lon": -84.389722222,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-staten-island",
    "name": "Staten Island",
    "lat": 40.571944444,
    "lon": -74.146944444,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-omaha",
    "name": "Omaha",
    "lat": 41.258611111,
    "lon": -95.9375,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-colorado-springs",
    "name": "Colorado Springs",
    "lat": 38.863333333,
    "lon": -104.791944444,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-raleigh",
    "name": "Raleigh",
    "lat": 35.78,
    "lon": -78.64,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-long-beach",
    "name": "Long Beach",
    "lat": 33.768055555,
    "lon": -118.195555555,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-virginia-beach",
    "name": "Virginia Beach",
    "lat": 36.8506,
    "lon": -75.9779,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-miami",
    "name": "Miami",
    "lat": 25.783333333,
    "lon": -80.216666666,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-oakland",
    "name": "Oakland",
    "lat": 37.8,
    "lon": -122.25,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-minneapolis",
    "name": "Minneapolis",
    "lat": 44.981944444,
    "lon": -93.269166666,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-tulsa",
    "name": "Tulsa",
    "lat": 36.131388888,
    "lon": -95.937222222,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-bakersfield",
    "name": "Bakersfield",
    "lat": 35.373333333,
    "lon": -119.018888888,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-wichita",
    "name": "Wichita",
    "lat": 37.688888888,
    "lon": -97.336111111,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-arlington",
    "name": "Arlington",
    "lat": 32.705033,
    "lon": -97.122839,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-aurora",
    "name": "Aurora",
    "lat": 39.710833333,
    "lon": -104.8125,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-tampa",
    "name": "Tampa",
    "lat": 27.9475,
    "lon": -82.458611111,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-new-orleans",
    "name": "New Orleans",
    "lat": 29.976111111,
    "lon": -90.078333333,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-cleveland",
    "name": "Cleveland",
    "lat": 41.499166666,
    "lon": -81.694722222,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-honolulu",
    "name": "Honolulu",
    "lat": 21.304722222,
    "lon": -157.857222222,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-anaheim",
    "name": "Anaheim",
    "lat": 33.836111111,
    "lon": -117.889722222,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-san-juan",
    "name": "San Juan",
    "lat": 18.465277777,
    "lon": -66.116666666,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-lexington",
    "name": "Lexington",
    "lat": 38.049722222,
    "lon": -84.458611111,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-stockton",
    "name": "Stockton",
    "lat": 37.9575,
    "lon": -121.2925,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-corpus-christi",
    "name": "Corpus Christi",
    "lat": 27.742777777,
    "lon": -97.401944444,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-henderson",
    "name": "Henderson",
    "lat": 36.031666666,
    "lon": -114.981388888,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-riverside",
    "name": "Riverside",
    "lat": 33.982222222,
    "lon": -117.3725,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-newark",
    "name": "Newark",
    "lat": 40.735555555,
    "lon": -74.172222222,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-saint-paul",
    "name": "Saint Paul",
    "lat": 44.944166666,
    "lon": -93.093611111,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-santa-ana",
    "name": "Santa Ana",
    "lat": 33.740833333,
    "lon": -117.881388888,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-cincinnati",
    "name": "Cincinnati",
    "lat": 39.1,
    "lon": -84.5125,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-irvine",
    "name": "Irvine",
    "lat": 33.684166666,
    "lon": -117.7925,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-orlando",
    "name": "Orlando",
    "lat": 28.533611111,
    "lon": -81.386666666,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-pittsburgh",
    "name": "Pittsburgh",
    "lat": 40.441666666,
    "lon": -80,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-st-louis",
    "name": "St. Louis",
    "lat": 38.626388888,
    "lon": -90.199444444,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-greensboro",
    "name": "Greensboro",
    "lat": 36.08,
    "lon": -79.819444444,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-jersey-city",
    "name": "Jersey City",
    "lat": 40.71,
    "lon": -74.06,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-city-anchorage",
    "name": "Anchorage",
    "lat": 61.216666666,
    "lon": -149.893611111,
    "badge": "US",
    "group": "city"
  },
  {
    "id": "us-cap-providence",
    "name": "Providence (Capital)",
    "lat": 41.82399,
    "lon": -71.41283,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-salt-lake-city",
    "name": "Salt Lake City (Capital)",
    "lat": 40.75,
    "lon": -111.883333333,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-albany",
    "name": "Albany (Capital)",
    "lat": 42.65,
    "lon": -73.766666666,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-harrisburg",
    "name": "Harrisburg (Capital)",
    "lat": 40.264554871,
    "lon": -76.883381676,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-trenton",
    "name": "Trenton (Capital)",
    "lat": 40.220277777,
    "lon": -74.765833333,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-montpelier",
    "name": "Montpelier (Capital)",
    "lat": 44.2658586,
    "lon": -72.5717415,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-jefferson-city",
    "name": "Jefferson City (Capital)",
    "lat": 38.576666666,
    "lon": -92.173611111,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-jackson",
    "name": "Jackson (Capital)",
    "lat": 32.298888888,
    "lon": -90.184722222,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-augusta",
    "name": "Augusta (Capital)",
    "lat": 44.310555555,
    "lon": -69.779444444,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-baton-rouge",
    "name": "Baton Rouge (Capital)",
    "lat": 30.4475,
    "lon": -91.178611111,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-lansing",
    "name": "Lansing (Capital)",
    "lat": 42.7335,
    "lon": -84.5467,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-concord",
    "name": "Concord (Capital)",
    "lat": 43.206666666,
    "lon": -71.538055555,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-lincoln",
    "name": "Lincoln (Capital)",
    "lat": 40.809166666,
    "lon": -96.678055555,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-annapolis",
    "name": "Annapolis (Capital)",
    "lat": 38.978611111,
    "lon": -76.491944444,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-springfield",
    "name": "Springfield (Capital)",
    "lat": 39.7975,
    "lon": -89.645,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-frankfort",
    "name": "Frankfort (Capital)",
    "lat": 38.197,
    "lon": -84.863,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-montgomery",
    "name": "Montgomery (Capital)",
    "lat": 32.3675,
    "lon": -86.3,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-juneau",
    "name": "Juneau (Capital)",
    "lat": 58.30194,
    "lon": -134.41972,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-little-rock",
    "name": "Little Rock (Capital)",
    "lat": 34.744444444,
    "lon": -92.288055555,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-hartford",
    "name": "Hartford (Capital)",
    "lat": 41.763333333,
    "lon": -72.685,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-dover",
    "name": "Dover (Capital)",
    "lat": 39.161662,
    "lon": -75.525709,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-boise",
    "name": "Boise (Capital)",
    "lat": 43.613611111,
    "lon": -116.237777777,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-tallahassee",
    "name": "Tallahassee (Capital)",
    "lat": 30.438333333,
    "lon": -84.280555555,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-bismarck",
    "name": "Bismarck (Capital)",
    "lat": 46.808333333,
    "lon": -100.78375,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-columbia",
    "name": "Columbia (Capital)",
    "lat": 34.000555555,
    "lon": -81.044166666,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-santa-fe",
    "name": "Santa Fe (Capital)",
    "lat": 35.666666666,
    "lon": -105.966666666,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-helena",
    "name": "Helena (Capital)",
    "lat": 46.592777777,
    "lon": -112.035,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-cheyenne",
    "name": "Cheyenne (Capital)",
    "lat": 41.145555555,
    "lon": -104.801944444,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-des-moines",
    "name": "Des Moines (Capital)",
    "lat": 41.590833333,
    "lon": -93.620833333,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-pierre",
    "name": "Pierre (Capital)",
    "lat": 44.368361111,
    "lon": -100.351138888,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-carson-city",
    "name": "Carson City (Capital)",
    "lat": 39.160833333,
    "lon": -119.753888888,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-topeka",
    "name": "Topeka (Capital)",
    "lat": 39.04833,
    "lon": -95.67804,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-olympia",
    "name": "Olympia (Capital)",
    "lat": 47.0425,
    "lon": -122.893055555,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-richmond",
    "name": "Richmond (Capital)",
    "lat": 37.540833333,
    "lon": -77.436666666,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-madison",
    "name": "Madison (Capital)",
    "lat": 43.074722222,
    "lon": -89.384166666,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-salem",
    "name": "Salem (Capital)",
    "lat": 44.930833333,
    "lon": -123.028888888,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "us-cap-charleston",
    "name": "Charleston (Capital)",
    "lat": 38.347222222,
    "lon": -81.633333333,
    "badge": "US",
    "group": "capital"
  },
  {
    "id": "gl-dallol",
    "name": "Dallol, Ethiopia",
    "lat": 14.242,
    "lon": 40.3,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-dasht-e-lut",
    "name": "Dasht-e Lut (Gandom Beryan), Iran",
    "lat": 30.6,
    "lon": 59.25,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-tamanrasset",
    "name": "Tamanrasset, Algeria (Sahara)",
    "lat": 22.785,
    "lon": 5.5228,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-kuwait-city",
    "name": "Kuwait City, Kuwait",
    "lat": 29.375,
    "lon": 47.98,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-basra",
    "name": "Basra, Iraq",
    "lat": 30.508,
    "lon": 47.78,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-jacobabad",
    "name": "Jacobabad, Pakistan",
    "lat": 28.281,
    "lon": 68.438,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-riyadh",
    "name": "Riyadh, Saudi Arabia",
    "lat": 24.713,
    "lon": 46.675,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-san-pedro-atacama",
    "name": "Atacama (San Pedro), Chile",
    "lat": -22.911,
    "lon": -68.202,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-vostok",
    "name": "Vostok Station, Antarctica",
    "lat": -78.464,
    "lon": 106.833,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-south-pole",
    "name": "South Pole (Amundsen–Scott Station)",
    "lat": -90,
    "lon": 0,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-dome-a",
    "name": "Dome A, Antarctica",
    "lat": -80.367,
    "lon": 77.35,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-alert",
    "name": "Alert, Nunavut, Canada",
    "lat": 82.5018,
    "lon": -62.3481,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-eureka",
    "name": "Eureka, Nunavut, Canada",
    "lat": 79.989,
    "lon": -85.939,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-oymyakon",
    "name": "Oymyakon, Russia",
    "lat": 63.464,
    "lon": 142.773,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-verkhoyansk",
    "name": "Verkhoyansk, Russia",
    "lat": 67.55,
    "lon": 133.39,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-norilsk",
    "name": "Norilsk, Russia",
    "lat": 69.355,
    "lon": 88.19,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-longyearbyen",
    "name": "Longyearbyen (Svalbard), Norway",
    "lat": 78.223,
    "lon": 15.646,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-mawsynram",
    "name": "Mawsynram, India",
    "lat": 25.298,
    "lon": 91.582,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-cherrapunji",
    "name": "Cherrapunji, India",
    "lat": 25.277,
    "lon": 91.732,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-debundscha",
    "name": "Debundscha, Cameroon",
    "lat": 4.087,
    "lon": 9.29,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-quibdo",
    "name": "Quibdó, Colombia",
    "lat": 5.694,
    "lon": -76.658,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-wellington",
    "name": "Wellington, New Zealand",
    "lat": -41.286,
    "lon": 174.776,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-punta-arenas",
    "name": "Punta Arenas, Chile",
    "lat": -53.163,
    "lon": -70.917,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-cape-denison",
    "name": "Cape Denison (Commonwealth Bay), Antarctica",
    "lat": -67,
    "lon": 142.65,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-tristan-da-cunha",
    "name": "Tristan da Cunha",
    "lat": -37.105,
    "lon": -12.277,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-everest-region",
    "name": "Everest region, Nepal",
    "lat": 28.002,
    "lon": 86.852,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-aconcagua-region",
    "name": "Aconcagua region, Argentina",
    "lat": -32.653,
    "lon": -70.011,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-k2-region",
    "name": "K2 region, Pakistan",
    "lat": 35.881,
    "lon": 76.513,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-tacloban",
    "name": "Tacloban, Philippines",
    "lat": 11.244,
    "lon": 125.004,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-naha",
    "name": "Okinawa (Naha), Japan",
    "lat": 26.212,
    "lon": 127.681,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-darwin",
    "name": "Darwin, Australia",
    "lat": -12.463,
    "lon": 130.845,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-reykjavik",
    "name": "Reykjavík, Iceland",
    "lat": 64.1466,
    "lon": -21.9426,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-rotorua",
    "name": "Rotorua, New Zealand",
    "lat": -38.136,
    "lon": 176.249,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-ushuaia",
    "name": "Ushuaia, Argentina",
    "lat": -54.801,
    "lon": -68.303,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-tromso",
    "name": "Tromsø, Norway",
    "lat": 69.649,
    "lon": 18.956,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-nuuk",
    "name": "Nuuk, Greenland",
    "lat": 64.181,
    "lon": -51.694,
    "badge": "Global",
    "group": "notable"
  },
  {
    "id": "gl-ulaanbaatar",
    "name": "Ulaanbaatar, Mongolia",
    "lat": 47.886,
    "lon": 106.905,
    "badge": "Global",
    "group": "notable"
  }
] as any;

export const LAND_POINTS_META = {
  pointsTotal: 152,
  pointsUs: 115,
  pointsGlobal: 37,
} as const;
